---
title: "Project"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#df <- read.csv(file = "C:/Users/leomi/Downloads/Data-mining/Project_CVTDM/onlinedeliverydata.csv", header = T, sep = ",")
setwd("C:/Users/andre/Desktop/Creating Value Project")
df <- read.csv("onlinedeliverydata.csv", header = TRUE, sep = ",")
df <- df[,-c(8,9,10)]
str(df)
attach(df)
```

## Recoding variables

```{r}
library(dplyr)

df1 <- df[,-52]

for (i in c(14:33,37:41)) {
  df1[,i] <- recode(df1[,i], "Strongly Agree"=5, "Agree"=4,"Neutral"=3,"Disagree"=2,"Strongly Disagree"=1)
}

library(naniar)
gg_miss_var(df1[,c(14:33,37:41)], show_pct = TRUE)

levels(df[,51])
df1$Output <- recode(df1$Output, "Yes"=1, "No"=0)
gg_miss_var(df[,50:51], show_pct = TRUE)

levels(as.factor(df1[,5]))
df1$Monthly.Income=recode(df$Monthly.Income, "10001 to 25000"=17500.5, "25001 to 50000"=37500, "Below Rs.10000" = 10000, "More than 50000"=50000, "No Income"=0 )

levels(df[,43])
str(df[,43:50])

for (i in c(43:50)) {
  df1[,i] <- recode(df1[,i], "Important"=4, "Moderately Important"=3, "Slightly Important"=2, "Unimportant"=1, "Very Important"=5)
}
gg_miss_var(df1[,43:50], show_pct = TRUE)

levels(df[,34])
str(df[,c(34,42)])
for (i in c(34,42)) {
  df1[,i] <- recode(df1[,i], "Maybe"=2, "No"=1, "Yes"=3)
}
gg_miss_var(df1[,c(34,42)], show_pct = TRUE)

levels(df[,2])
df1$Gender <- recode(df1$Gender, "Female"=1, "Male"=0)
gg_miss_var(df1[,1:2], show_pct = TRUE)



df1=df1[,-c(8:13)]
str(df1)
```

## Data frames

```{r}
df2 <- df1[,c(1,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,27,30,36,38,39,40,41,45)]
str(df2)
```

## Dummies

```{r}
df2$Marital.Status =as.factor(df2$Marital.Status)
df2$Occupation=as.factor(df2$Occupation)
df2$Educational.Qualifications=as.factor(df2$Educational.Qualifications)

library(caret)
dummies=dummyVars(~., data=df2)
df.dummy=as.data.frame(predict(dummies, newdata=df2))

df.dummy=df.dummy[,-c(3,6,14)]
str(df.dummy)
```

```{r}
df.dummy$Output <- as.factor(df.dummy$Output)
df2$Output <- as.factor(df2$Output)
```

## Partitioning

```{r}
library(caret)

set.seed(1)
train_rows <- createDataPartition(df2$Output, p = .5, list = FALSE)
train <- df2[train_rows,]
valid_test <- df2[-train_rows,]
set.seed(1)
valid_rows <- createDataPartition(valid_test$Output, p = .6, list = FALSE)
valid <- valid_test[valid_rows,]
test <- valid_test[-valid_rows,]
```

```{r}
set.seed(1)
train_rows1 <- createDataPartition(df.dummy$Output, p = .5, list = FALSE)
train.dummy <- df.dummy[train_rows1,]
valid_test.dummy <- df.dummy[-train_rows1,]
set.seed(1)
valid_rows1 <- createDataPartition(valid_test.dummy$Output, p = .6, list = FALSE)
valid.dummy <- valid_test.dummy[valid_rows1,]
test.dummy <- valid_test.dummy[-valid_rows1,]
```


```{r}
print(table(train$Output) / table(df2$Output)) #Training set partition
print(table(valid$Output) / table(df2$Output)) #Validation set partition
print(table(test$Output) / table(df2$Output)) #Test set partition
```













